### ISSUE TITLE
[Lisboa] Senior RPA Engineer na ClaraNet Portugal

### ISSUE THREAD

**Issue by AlexClaranetPortugal** [chatbotbr/vagas#2]
## Nossa empresa

Fundada em 1996, a Claranet é o maior fornecedor de serviços de tecnologias de informação em Portugal, especialista em soluções de Cloud, Security, Dados e Workplace.

Hoje, conta mais de 2.500 colaboradores em 10 países (Reino Unido, Portugal, Brasil, França, Alemanha, Holanda, Espanha, Itália, Suíça e USA), 24 escritórios e 45 datacenters, dos quais 2 em Portugal.

A Claranet tem como missão global construir uma relação de confiança duradoura com cada um dos seus clientes, ajudando-os a focar os seus recursos na inovação e criação de valor para o seu negócio.

Mais informações em [www.claranet.pt](http://www.claranet.pt/)

## Descrição da vaga

Posição de RPA Engineer com experiência em Automation Anywhere. Se conhece o AA, só vem!

## Local

Híbrido [Lisboa]

## Requisitos

**Obrigatórios:**

- ~2 anos de experiência com AA
- ~3 anos de experiência com RPA Engineering
- Inglês avançado ou fluente para o dia-a-dia.

## Benefícios

- Plano de saúde
- VR
- Auxílio benefícios

**Diferenciais:**

- Custos de visto pagos
- Hospedagem inicial paga
- Interface com toda a Europa

## Contratação

"CLT" modelo português

## Como se candidatar

Por favor envie um email para alexander.giffoni@pt.clara.net com seu CV anexado - enviar no assunto: Vaga RPA Engineer

## Tempo médio de feedbacks

Eu respondo as mensagens assim que as vejo, em no máximo 1 dia.

- Híbrido
- CLT
- Senior
- Especialista

**Comment by arthurfigueiredo** [comment]
Vaga não está de acordo com as diretrizes do repositório
